ansible_user: arista
ansible_password: arista
ansible_network_os: eos
ansible_connection: httpapi
ansible_become: true
ansible_become_method: enable


domain_name: atd.local
dns_server: 192.168.0.4
ntp_server: time.google.com
timezone: America/Detroit