---

- name: Play 1 - Set System Information
  hosts: arista
  gather_facts: no

  tasks:

    - name: Task 1 - Set Hostname and Domain Name
      eos_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"

    - name: Task 2 - Set DNS Server, Set Lookup Source to Mgmt1
      eos_system:
        name_servers:
          - "{{ dns_server }}"
        lookup_source:
          - interface: Management1
      tags: dns

    - name: Task 3 - Set NTP Server
      eos_config:
        lines: 
          - ntp server {{ ntp_server }} prefer
          - clock timezone {{ timezone }}
      tags: ntp

- name: Play 2 - Get Information About Host
  hosts: arista
  gather_facts: no

  tasks:

    - name: Task 1 - Gather EOS Facts
      eos_facts:



- name: Play 3 - Configure Spine/Leaf Interfaces
  hosts: arista
  gather_facts: no

  tasks:

    - name: Task 1 - Set Interface Descriptions
      tags: intdesc
      eos_config:
        src: ./templates/intdesc.j2

    - name: Task 2 - Set Loopback Interface IP Addresses
      tags: loopips
      eos_config:
        src: ./templates/loopips.j2

    - name: Task 3 - Set Interface IP Addresses
      tags: intips
      eos_config:
        src: ./templates/intips.j2



- name: Play 4 - Configure OSPF
  hosts: arista
  gather_facts: no

  tasks:

    - name: Task 1 - Configure the OSPF Process
      tags: ospfproc
      eos_config:
        src: ./templates/ospfproc.j2

    - name: Task 2 - Enable OSPF on Interfaces
      tags: ospfints
      eos_config:
        src: ./templates/ospfints.j2
