---

- name: Play 1 - Enable eAPI
  hosts: ospf
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:

    - name: enable eAPI
      eos_eapi:
    
    - name: No Shut eAPI
      eos_config:
        lines:
          - no shutdown
          - protocol http
        parents: management api http-commands

- name: Play 2 - Cleanup Configs
  hosts: eos5,eos8
  gather_facts: no

  tasks:

    - name: Cleanup configs
      eos_config:
        src: ./configs/cleanup.cfg


- name: Play 3 - Applying Base IPv4 Configuration for OSPF Class
  hosts: ospf
  gather_facts: no

  tasks:

    - name: Gather EOS Facts
      eos_facts:

    - name: Apply Base IPv4 Configuration
      eos_config:
        src: ./configs/{{inventory_hostname}}.cfg


- name: Play 4 - Enabling Base OSPF Configuration
  hosts: ospf
  gather_facts: no

  tasks:

    - name: Create OSPF process and enable OSPF on Lo0
      eos_config:
        src: ./templates/ospfinitial.j2
      tags: ospfinit


- name: Play 5 - Update LabAccess Login Script
  hosts: localhost
  become: yes

  tasks:

    - name: Copy ospflogin.py to /usr/local/bin
      copy:
        src: ospflogin.py
        dest: /usr/local/bin/login.py
        mode: 0777
      tags: login