---

- name: Play 1 - Deploy mucho routes to Spine1 and Spine2
  hosts: spine1,spine2
  gather_facts: no

  tasks:

    - name: Task 1 - Blast Routes
      eos_config:
        src: "{{ playbook_dir }}/templates/RouteBlaster.j2"

